(INFC-17763) Support Windows
ploperations/ploperations-ssh pull request #7
Opened 2018-12-31 09:04 UTC by danielparks

This refactors the code and makes extensive changes to support both [native][] and Cygwin OpenSSH on Windows.

All that is required to release 1.0 is documentation, so this bumps the version to 0.9.0.

This is built on top of https://github.com/ploperations/ploperations-ssh/pull/4 and https://github.com/ploperations/ploperations-ssh/pull/3.

[native]: https://github.com/PowerShell/openssh-portable

2018-12-31 14:12 UTC, genebean requested changes

2018-12-31 14:12 UTC, genebean commented on manifests/params.pp
> +        $_programdata = $facts.get('windows_env.PROGRAMDATA')
`facts.get()` doesn't work pre-puppet 6

2018-12-31 14:12 UTC, genebean commented on manifests/server/windows/chocolatey.pp
> +  Stdlib::Absolutepath  $default_shell                = "${facts.get('windows_env.WINDIR')}\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
`facts.get()` doesn't work pre-puppet 6

2018-12-31 14:12 UTC, genebean commented on manifests/server/windows/cygwin.pp
> +  $windir = $facts.get('windows_env.WINDIR')
`facts.get()` doesn't work pre-puppet 6

2019-01-04 04:24 UTC, danielparks commented on spec/spec_helper.rb
> +
These will be overwritten by PDK — see https://github.com/puppetlabs/pdk-templates#specspec_helperrb.

2019-01-11 17:48 UTC, genebean commented
@danielparks are you ready for another review yet or is this still a WIP?

2019-01-17 10:00 UTC, danielparks commented
I'll reopen this when it's ready.

2019-01-17 10:00 UTC, closed without merging